apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
    - name: Mimir
      type: prometheus
      access: proxy
      url: http://grafana-mimir:9009/prometheus  
      jsonData:
        httpMethod: POST
    - name: Tempo
      type: tempo
      url: http://tempo:3200
      access: proxy
      isDefault: false