apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        args:
          - "-config.file=/etc/loki/loki.yaml"
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: config-volume
          mountPath: "/etc/loki"
        - name: loki-storage
          mountPath: "/loki"
      volumes:
      - name: config-volume
        configMap:
          name: loki-config
      - name: loki-storage
        emptyDir: {}  # Temporary storage, consider PVC for production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    schema_config:
      configs:
        - from: 2025-03-25  # Update to current date
          store: tsdb       # Changed from boltdb-shipper
          object_store: filesystem
          schema: v13       # Updated from v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      tsdb_shipper:         # Changed from boltdb_shipper
        active_index_directory: /loki/tsdb-index
        cache_location: /loki/tsdb-cache
        cache_ttl: 24h
      filesystem:
        directory: /loki/chunks
    compactor:
      working_directory: /loki/compactor
    limits_config:
      allow_structured_metadata: false  # Temporary until properly configured

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  ports:
  - port: 3100
    targetPort: 3100
  selector:
    app: loki