# pg-exporter-deployment.yaml (in monitoring namespace)
apiVersion: v1
kind: Secret
metadata:
  name: pg-exporter-secrets
  namespace: monitoring
type: Opaque
data:
  username: YWRtaW4=  # base64 "admin"
  password: c2VjcmV0cGFzc3dvcmQ=  # base64 "secretpassword"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-exporter
  template:
    metadata:
      labels:
        app: pg-exporter
    spec:
      containers:
      - name: pg-exporter
        image: quay.io/prometheuscommunity/postgres-exporter:latest
        args:
        - --web.listen-address=:9187
        - --web.telemetry-path=/metrics
        env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://admin:secretpassword@postgres.application.svc.cluster.local:5432/monitoring_demo?sslmode=disable"
        ports:
        - containerPort: 9187
          
---
apiVersion: v1
kind: Service
metadata:
  name: pg-exporter-service
  namespace: monitoring
spec:
  ports:
  - port: 9187
    targetPort: 9187
  selector:
    app: pg-exporter
  type: NodePort